src.dir=src/main/java
web.dir=src/main/webapp
lib.dir=lib
test.dir=src/test/java

build.dir=build/ant
classes.dir=build/ant/classes
test.classes.dir=build/ant/test-classes

jar.name=lab3.jar
version=1.0.0
main.class=lab.MainDummy

scp.host=roflex.su
scp.port=4242
scp.user=roflex
scp.dir=/home/roflex/ITMO/OPI-3

svn.user=roflex
diff.forbidden.classes=AreaBean|Result

alt.build.dir=build/alt

resources.dir=src/main/resources

sound.dir=ant/sounds
sound.success=success.wav
sound.fail=fail.wav

alt.build.dir=build/alt
alt.src.dir=${alt.build.dir}/src
alt.classes.dir=${alt.build.dir}/classes
alt.jar.name=lab3-alt.jar

alt.token.class.old=AreaBean
alt.token.class.new=SuperAreaBean
alt.token.var.old=checkHit
alt.token.var.new=validateHit
