# Директории исходников
src.dir=src/main/java
web.dir=src/main/webapp
lib.dir=lib
test.dir=src/test/java

# Директории сборки
build.dir=build/ant
classes.dir=build/ant/classes
test.classes.dir=build/ant/test-classes

# Параметры архива (требование MANIFEST.MF)
jar.name=lab3.jar
version=1.0.0
# JSF-приложения обычно не запускаются как консольные,
# но для выполнения требования нужен класс с методом main (потом создашь заглушку)
main.class=lab.MainDummy

# Настройки для SCP (цель 7)
scp.host=roflex.su
scp.port=4242
scp.user=roflex
scp.dir=/home/roflex/ITMO/OPI-3

# Настройки для alt (цель 9)
alt.build.dir=build/alt

# Локализация
resources.dir=src/main/resources

# Звуки для сборки
sound.dir=ant/sounds
sound.success=success.wav
sound.fail=fail.wav

# Настройки для цели alt
alt.build.dir=build/alt
alt.src.dir=${alt.build.dir}/src
alt.classes.dir=${alt.build.dir}/classes
alt.jar.name=lab3-alt.jar

# Токены для замены (меняем класс AreaBean и метод checkHit)
alt.token.class.old=AreaBean
alt.token.class.new=SuperAreaBean
alt.token.var.old=checkHit
alt.token.var.new=validateHit